### PR TITLE
add feature to set Skull Texture in ItemBuilder

### PR DESCRIPTION
**Pull request by btwonion**

### CODE REVIEW

**Comment by btwonion** [comment]
sorry the commits are wrong. only the second should show up xD

**Comment by jakobkmar** [comment]
does this compile? seems like it was made in githubs web editor again - so probably some imports are missing

**Comment by btwonion** [comment]
oh yeah i forgot the imports. i'll fix it.

**Comment by r0yzer** [comment]
soll vorkommen

**Comment by btwonion** [comment]
now it should be fixed

**Comment by jakobkmar** [comment]
I will merge this for now and test it later (for sure hehe).

**Comment by btwonion** [comment]
okay. i tested it like 3 times now. it's stable xD

**Pull request merged**
